#!/usr/bin/env python
print('.     .       .  .   . .   .   . .    +  .')
print('  .     .  :     .    .. :. .___---------___.')
print('       .  .   .    .  :.:. _ .^ .^ ^.  . . :_. .')
print('    .  :       .  .  .:../:            . .^  :.:\.')
print('        .   . ::  . :.:/: .   .    .        . . .:\.')
print(' .  :    .     . _ :::/:               .  ^ .  . .:\/')
print('  .. . .   . - : :.:./.                        .  .:\/')
print('  .      .     . :..|:                    .  .  ^. .:|')
print('    .       . : : ..||        .                . . !:|')
print('  .     . . . ::. ::\(                           . :)/')
print(' .   .     : . : .:.|. ######               #######::|')
print('  :.. .  :-  : .:  ::|.#######           ..########:|')
print(' .  .  .  ..  .  .. :\ ########          :######## :/')
print('  .        .+ :: : -.:\ ########       . ########.:/')
print('    .  .+   . . . . :.:\. #######       #######..:/')
print('      :: . . . . ::.:..:.\           .   .   ..:/')
print('   .   .   .  .. :  -::::.\.       | |     . .:/')
print('      .  :  .  .  .-:.":.::.\             ..:/')
print(' .      -.   . . . .: .:::.:.\.           .:/')
print('.   .   .  :      : ....::_:..:\   ___.  :/')
print('   .   .  .   .:. .. .  .: :.:.:\       :/')
print('     +   .   .   : . ::. :.:. .:.|\  .:/|')
print('     .         +   .  .  ...:: ..|  --.:|')
print('.      . . .   .  .  . ... :..:.."(  ..)"')
print(' .   .       .      :  .   .: ::/  .  .::\.')
def inter_graf(linha_repet):
    print(linha_repet)
inter_graf('_' *90);print('VERSION: 1.0 (((TEXTFIL)))      By: Edward Ramos        Date: 01032017');inter_graf('_' *90)
print('OPTION   |                          DESCRIPTION(filters)\n')
print('  1      -    cat  +Usado para mostrar o conteudo de arquivos, do inicio ao final: ')
